import Head from 'next/head'
import Hero from '../components/Hero'
import Slider from '../components/Slider'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Photos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-[150vh]'>
        <Hero heading='Next Photography' message='I capture moments in nature and keep them alive.'/>
        <Slider />
      </main>
    </>
  )
}
